export const shopData = [
	{
		id: "1",
		title: "福岡",
		subTitle: "",
		menu: "福岡めんたいもつ鍋/博多水炊き",
		description: "",
		image: "/assets/shop/shop1.png",
		image2: "/assets/shop/shop2.png",
	},
	{
		id: "2",
		title: "京都",
		subTitle: "",
		menu: "京鴨鍋/京すき焼き（松坂牛）",
		description: "",
		image: "/assets/shop/shop3.png",
		image2: "/assets/shop/shop4.png",
	},
	{
		id: "3",
		title: "北海道",
		subTitle: "",
		menu: "釧路カニ鍋/石狩鍋",
		description: "",
		image: "/assets/shop/shop5.png",
		image2: "/assets/shop/shop6.png",
	},
	{
		id: "4",
		title: "茨城/石川",
		subTitle: "",
		menu: "大洗あんこう鍋/能登ぶり鍋",
		description: "",
		image: "/assets/shop/shop7.png",
		image2: "/assets/shop/shop22.jpeg",
	},
	{
		id: "5",
		title: "横浜",
		subTitle: "",
		menu: "中華街トマト鍋/中華街麻辣鍋",
		description: "",
		image: "/assets/shop/shop8.png",
		image2: "/assets/shop/shop9.png",
	},
	{
		id: "6",
		title: "広島/山口",
		subTitle: "",
		menu: "広島牡蠣鍋/下関ふぐちり",
		description: "",
		image: "/assets/shop/shop10.png",
		image2: "/assets/shop/shop11.png",
	},
	{
		id: "7",
		title: "秋田/岐阜",
		subTitle: "",
		menu: "秋田きりたんぽ鍋/各務原キムチの鍋",
		description: "",
		image: "/assets/shop/shop12.png",
		image2: "/assets/shop/shop13.png",
	},
	{
		id: "8",
		title: "山形/宮城",
		subTitle: "",
		menu: "山形芋煮鍋/仙台セリ鍋",
		description: "",
		image: "/assets/shop/shop14.png",
		image2: "/assets/shop/shop15.png",
	},
	{
		id: "9",
		title: "東京/愛媛",
		subTitle: "",
		menu: "両国ちゃんこ鍋/愛媛キジ鍋",
		description: "",
		image: "/assets/shop/shop16.png",
		image2: "/assets/shop/shop17.png",
	},
	{
		id: "10",
		title: "群馬/長野",
		subTitle: "",
		menu: "高崎もつ煮/信州キノコ鍋",
		description: "",
		image: "/assets/shop/shop18.png",
		image2: "/assets/shop/shop19.png",
	},
	{
		id: "11",
		title: "三重/千葉",
		subTitle: "",
		menu: "三重イセエビ鍋/千葉漁師鍋",
		description: "",
		image: "/assets/shop/shop23.jpeg",
		image2: "/assets/shop/shop20.jpeg",
	},
	{
		id: "12",
		title: "ビール/スイーツ",
		subTitle: "",
		menu: "サッポロクラッシク/綿菓子",
		description: "",
		image: "/assets/shop/shop30.jpg",
		image2: "/assets/shop/shop31.jpg",
		imgClass: "object-contain max-h-[192px]",
	},
	{
		id: "13",
		title: "VIP",
		subTitle: "",
		menu: "しゃぶしゃぶ",
		description: "",
		image: "/assets/shop/shop21.png",
		image2: "/assets/menu/menu13_4.jpeg",
	},
];

export const foodData = [
	{
		id: "1",
		info: [
			{
				title: "明太子",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "やわら角煮",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "中津唐揚げ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "2",
		info: [
			{
				title: "くるくる鳥皮焼",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "地鶏炭火焼",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "鶏飯",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "3",
		info: [
			{
				title: "鴨のパストラミ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ねぎ焼",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "牛すじ煮込み",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "4",
		info: [
			{
				title: "京都おでん",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "京ぜんざい",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "京漬物",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "5",
		info: [
			{
				title: "帆立焼",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "蟹甲羅焼",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "じゃがバター",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "6",
		info: [
			{
				title: "タコざんぎ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ジンギスカン",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ラムチョップ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "10",
		info: [
			{
				title: "牡蛎フライ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "蒸牡蛎",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "牡蛎バター",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "11",
		info: [
			{
				title: "ふぐ唐揚げ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ふぐ焼売",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ふぐ皮ポン酢",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "12",
		info: [
			{
				title: "綿菓子",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "いちご りんご飴",
				price: "",
				catchcopy: "",
				description: "",
				image: "/assets/menu/menu_a1.jpg",
				imgClass: "object-contain",
			},
			{
				title: "チュロス",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "13",
		info: [
			{
				title: "牛しゃぶしゃぶ",
				price: "",
				catchcopy: "",
				description: "",
				image: "/assets/menu/menu13_5.png",
			},
			{
				title: "豚しゃぶしゃぶ",
				price: "",
				catchcopy: "",
				description: "",
				image: "/assets/menu/menu13_4.jpeg",
			},
			{
				title: "ぶりしゃぶしゃぶ",
				price: "",
				catchcopy: "",
				description: "",
				image: "/assets/menu/menu13_2.jpeg",
			},
			{
				title: "蟹しゃぶしゃぶ",
				price: "",
				catchcopy: "",
				description: "",
				image: "/assets/menu/menu13_3.jpeg",
			},
			{
				title: "たこしゃぶしゃぶ",
				price: "",
				catchcopy: "",
				description: "",
				image: "/assets/menu/menu13_1.jpeg",
			},
		],
	},
	{
		id: "16",
		info: [
			{
				title: "串揚げ盛り合わせ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "エビ串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ササミ串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "うずら串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "豚ロース串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "アナゴ一本揚げ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "牛たん串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "焼きとん串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ノンアルコールビール",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 屋守",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "17",
		info: [
			{
				title: "名物じゃこ天",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "せんざんぎ【愛媛からあげ】",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "今治甘辛ダレの焼き鳥",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "揚げあし鳥",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ノンアルコールビール",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 石鎚 純米吟醸",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 伊予賀儀屋 熟成 純米 無濾過",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "【栄光酒造】蔵元のみかん",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "18",
		info: [
			{
				title: "上州こんにゃくおでん",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "嬬恋ロールキャベツおでん",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "嬬恋キャベツのピクルス",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "上州ねぎガツポン",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "麦豚ガーリックバターソテー",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "もつ煮",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "下仁田ネギの丸ごとじゃんじゃん焼き",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 川中島",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 亀の海",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "そば焼酎",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "19",
		info: [
			{
				title: "信州野沢菜漬け",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "長野美味（おい）だれ焼き鳥",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "舞茸のバターソテー",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "きのことアスパラ炒め",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "信州サーモンのホイル焼き",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "信州みそ牛たん焼き",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ノンアルコールビール",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 町田酒造55 特別純米五百万石直波",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 水芭蕉 純米吟醸",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "群馬の地酒 本格米焼酎 ぎん草津",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "20",
		info: [
			{
				title: "くじらベーコン",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "チョリソー",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "蛤汁",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "はまぐりの酒蒸し",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "あじフライ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "イカバター醤油焼き",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ノンアルコールビール",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "甲子（きのえね）純米 うまから 磨き八割 千葉県",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "不動 純米超辛口 1800ml 【日本酒】",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "九十九里浜七福神 米焼酎",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "23",
		info: [
			{
				title: "伊勢えびバター焼き",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "三重焼き鳥つくね",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "焼き鳥アスパラベーコン",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "三重焼き鳥皮",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "はまぐりの酒蒸し",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "チーズフライ",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "エビ串",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "日本酒 地酒 三重県 鈴鹿市 清水清三郎商店 ザク ZAKU",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "瀧自慢 滝水流 はやせ 辛口一徹純米",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "半蔵の梅酒 【三重の有名酒蔵】",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "30",
		info: [
			{
				title: "レモンサワー",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハイボール",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "31",
		info: [
			{
				title: "綿菓子",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "いちご りんご飴",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "チュロス",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
];
