export const shopData = [
	{
		id: "1",
		title: "福岡①",
		subTitle: "",
		menu: "めんたいもつ鍋",
		description: "",
		image: "/assets/shop/shop1.png",
	},
	{
		id: "2",
		title: "福岡②",
		subTitle: "",
		menu: "水炊き",
		description: "",
		image: "/assets/shop/shop2.png",
		imgClass: "",
	},
	{
		id: "3",
		title: "京都①",
		subTitle: "",
		menu: "鴨鍋",
		description: "",
		image: "/assets/shop/shop3.png",
	},
	{
		id: "4",
		title: "京都②",
		subTitle: "",
		menu: "すき焼き（松阪牛）",
		description: "",
		image: "/assets/shop/shop4.png",
	},
	{
		id: "5",
		title: "北海道①",
		subTitle: "",
		menu: "カニ鍋",
		description: "",
		image: "/assets/shop/shop5.png",
	},
	{
		id: "6",
		title: "北海道②",
		subTitle: "",
		menu: "石狩鍋",
		description: "",
		image: "/assets/shop/shop6.png",
	},
	{
		id: "7",
		title: "茨城",
		subTitle: "",
		menu: "あんこう鍋",
		description: "",
		image: "/assets/shop/shop7.png",
	},
	{
		id: "8",
		title: "横浜①",
		subTitle: "",
		menu: "トマト中華鍋",
		description: "",
		image: "/assets/shop/shop8.png",
	},
	{
		id: "9",
		title: "横浜②",
		subTitle: "",
		menu: "麻辣鍋",
		description: "",
		image: "/assets/shop/shop9.png",
	},
	{
		id: "10",
		title: "広島",
		subTitle: "",
		menu: "牡蠣鍋",
		description: "",
		image: "/assets/shop/shop10.png",
	},
	{
		id: "11",
		title: "山口",
		subTitle: "",
		menu: "ふぐちり",
		description: "",
		image: "/assets/shop/shop11.png",
	},
	{
		id: "12",
		title: "秋田",
		subTitle: "",
		menu: "きりたんぽ鍋",
		description: "",
		image: "/assets/shop/shop12.png",
	},
	{
		id: "13",
		title: "岐阜",
		subTitle: "",
		menu: "各務原キムチ鍋",
		description: "",
		image: "/assets/shop/shop13.png",
	},
	{
		id: "14",
		title: "山形",
		subTitle: "",
		menu: "いも煮鍋",
		description: "",
		image: "/assets/shop/shop14.png",
	},
	{
		id: "15",
		title: "宮城",
		subTitle: "",
		menu: "せり鍋",
		description: "",
		image: "/assets/shop/shop15.png",
	},
	{
		id: "16",
		title: "東京",
		subTitle: "",
		menu: "ちゃんこ鍋",
		description: "",
		image: "/assets/shop/shop16.png",
	},
	{
		id: "17",
		title: "愛媛",
		subTitle: "",
		menu: "キジ鍋",
		description: "",
		image: "/assets/shop/shop17.png",
	},
	{
		id: "18",
		title: "群馬",
		subTitle: "",
		menu: "もつ煮",
		description: "",
		image: "/assets/shop/shop18.png",
	},
	{
		id: "19",
		title: "長野",
		subTitle: "",
		menu: "キノコ鍋",
		description: "",
		image: "/assets/shop/shop19.png",
	},
	{
		id: "20",
		title: "千葉",
		subTitle: "",
		menu: "イセエビ鍋",
		description: "",
		image: "/assets/shop/shop20.png",
	},
	{
		id: "21",
		title: "VIP",
		subTitle: "",
		menu: "しゃぶしゃぶ",
		description: "",
		image: "/assets/shop/shop21.png",
	},
];

export const foodData = [
	{
		id: "81",
		info: [
			{
				title: "魯肉飯（ルーローハン）",
				price: "600/800",
				catchcopy: "「台湾の香りを一口で！絶品ルーローハン",
				description: "甘辛いとろとろ豚肉の八角は入った台湾の定番料理！",
				image: "/assets/common/sample.png",
			},
			{
				title: "排骨飯（パイコーハン）",
				price: "800/1100",
				catchcopy: "サクサクジューシー！",
				description: "サクサクな衣の中にはジューシーな肉汁がたっぷり！",
				image: "",
			},
			{
				title: "排骨湯（パーコースープ）",
				price: "800",
				catchcopy: "栄養満点！台湾の家庭の味！",
				description: "豚の骨付き肉を使った栄養満点のスープ！",
				image: "",
			},
		],
	},
	{
		id: "82",
		info: [
			{
				title: "牛肉麵（ニュウロウミェン）",
				price: "900/1100",
				catchcopy: "台湾伝統の麺料理！",
				description:
					"台湾で最もポピュラーな麺料理！牛骨ベースの味がクセになる！",
				image: "",
			},
			{
				title: "排骨（パーコー）麺",
				price: "900/1300",
				catchcopy: "香ばしくてコク深い台湾味！",
				description: "香ばしい揚げ豚肉がのった、コク旨スープの台湾ラーメン",
				image: "",
			},
			{
				title: "牛汁そば",
				price: "800",
				catchcopy: "夏に食べたいさっぱり味！",
				description: "健康的かつさっぱりしてるので暑い日にはピッタリ！",
				image: "/assets/common/sample.png",
			},
		],
	},
	{
		id: "83",
		info: [
			{
				title: "豆乳スープ&油揚げパン",
				price: "800",
				catchcopy: "伝統的な朝食",
				description:
					"豆乳ベースのスープにサクサク揚げパンを浸して食べる台湾の定番料理",
				image: "/assets/common/sample.png",
			},
			{
				title: "油篠（あげパン）蜂蜜　きな粉",
				price: "600",
				catchcopy: "甘くて美味しい！",
				description: "台湾でもポピュラーな揚げパン！",
				image: "/assets/common/sample.png",
			},
			{
				title: "瀑布拉絲玉米（ナイアガラチーズコーン）",
				price: "1200",
				catchcopy: "とろけるチーズ&コーン！",
				description:
					"今、台湾の夜市で大人気！チーズとコーンの組み合わせが抜群！",
				image: "",
			},
			{
				title: "吉拿棒（チロスボールパフェ チロスボール）",
				price: "1000/600",
				catchcopy: "可愛い見た目で大人気！",
				description: "みんな大好きロングチュロス！子供にも大人気！",
				image: "",
			},
			{
				title: "",
				price: "",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "84",
		info: [
			{
				title: "大拝骨（ダージーパイ）鶏排",
				price: "700",
				catchcopy: "食べ応え抜群！",
				description:
					"大人気！台湾のからあげ「大鶏排」ザクザク食感をお楽しみください！",
				image: "",
			},
			{
				title: "杏鮑菇(焼エリンギ）",
				price: "600",
				catchcopy: "台湾屋台で大行列メニュー！",
				description:
					"台湾夜市で流行りのメニュー！甘醤油ベースに一口サイズにカットしたエリンギがくせになる！",
				image: "",
			},
			{
				title: "龍捲風洋芋片（トルネードポテト）",
				price: "600",
				catchcopy: "カリッと食感！見た目もかわいい！",
				description: "じゃがいもを螺旋状にカットした屋台の定番メニュー！",
				image: "",
			},
		],
	},
	{
		id: "85",
		info: [
			{
				title: "和牛麻婆豆腐/和牛麻婆豆腐丼",
				price: "800/1000",
				catchcopy: "岩崎健四郎監修和牛麻婆豆腐",
				description: "飲食業界のカリスマ岩崎健四郎監修の和牛麻婆豆腐",
				image: "",
			},
			{
				title: "ドラゴンロングポテト(スイートチリ/ノリ塩",
				price: "800",
				catchcopy: "カリッとホクホク！なが～いロングポテト",
				description:
					"30cmほどの長～いロングポテト！お友達や家族ともシェアして楽しもう！",
				image: "",
			},
			{
				title: "揚げ黒胡麻団子",
				price: "600",
				catchcopy: "台湾製黒胡麻団子",
				description: "周りのサクサク胡麻に中のモチモチ食感の餅に甘い餡",
				image: "",
			},
		],
	},
	{
		id: "86",
		info: [
			{
				title: "大籠包/焼小籠包",
				price: "800",
				catchcopy: "焼きたて小籠包",
				description: "夏でも食べたい！熱々焼きたて小籠包！",
				image: "",
			},
			{
				title: "海鮮焼売",
				price: "800",
				catchcopy: "海鮮の風味香る！",
				description: "中にはジューシーな海鮮がいっぱい！",
				image: "",
			},
			{
				title: "台湾胡瓜漬け",
				price: "600",
				catchcopy: "ピリ辛味付けが美味しい！",
				description:
					"夏の暑さを吹き飛ばす！台湾きゅうりの漬物！ピリ辛な味付けでおつまみにもピッタリ！",
				image: "",
			},
		],
	},
];
